version: '2'
services:
  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: .
    command: bundle exec ruby app.rb -e production
    volumes:
      - .:/myapp
    ports:
      - "4567:4567"
    depends_on:
      - db
