version: '2'
services:
  db:
    image: postgres_db
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - .:/phoenixapp
    ports:
      - "4000:4000"
    depends_on:
      - db
