version: '2'
services:
  db:
    image: postgres:9.5.4
    volumes:
      - ./db/postgres:/ver/lib/postgresql/data
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - .:/phoenixapp
    ports:
      - "4000:4000"
    depends_on:
      - db
